from ctypes import *

class BuySellLevelInfo3(Structure):
     _fields_ = [("Price", c_double),
                ("Volume", c_uint64),
                ("TotalOrderNo", c_int32)]


class AuctionUpDown(Structure):
    _fields_ = [("LimitUpRate", c_double),
                ("LimitDownRate", c_double),
                ("LimitUpAbsolute", c_double),
                ("LimitDownAbsolute", c_double),
                ("AuctionUpDownRate", c_double),
                ("AuctionUpDownAbsolute", c_double)]


class SZSE_BuySellLevelInfo3(Structure):
     _fields_ = [("Price", c_double),
                ("Volume", c_double),
                ("TotalOrderNo", c_int64)]


class SSEL2_Static(Structure):
    _fields_ = [("QDSTime", c_uint64), 
                ("Reserved", c_int64),
                ("Time", c_int32),
                ("Symbol", c_char * 40),
                ("ISINCode", c_char * 12),
                ("SecurityName", c_char * 20),
                ("SecurityEN", c_char * 24),
                ("SymbolUnderlying", c_char * 40),
                ("MarketType", c_char * 6),
                ("CFICode", c_char * 6),
                ("SecuritySubType", c_char * 6),
                ("Currency", c_char * 5),
                ("ParValue", c_double),
                ("TradableNo", c_int64),
                ("EndDate", c_int32),
                ("ListingDate", c_int32),
                ("SetNo", c_uint32),
                ("BuyVolumeUnit", c_uint32),
                ("SellVolumeUnit", c_uint32),
                ("DeclareVolumeFloor", c_uint32),
                ("DeclareVolumeCeiling", c_uint32),
                ("PreClosePrice", c_double),
                ("TickSize", c_double),
                ("UpDownLimitType", c_char),
                ("PriceUpLimit", c_double),
                ("PriceDownLimit", c_double),
                ("XRRatio", c_double),
                ("XDAmount", c_double),
                ("CrdBuyUnderlying", c_char),
                ("CrdSellUnderlying", c_char),
                ("SecurityStatus", c_char * 20),
                ("SampleAvgPrice", c_uint32),
                ("TradeAmount", c_double),
                ("AvgCapital", c_double),
                ("TotalMarketValue", c_double),
                ("MarketValueRatio", c_double),
                ("StaticPERatio", c_double),
                ("IndexLevelStatus", c_char * 20)]

class SSEL2_Quotation(Structure):
     _fields_ = [("QDSTime", c_uint64), 
                ("Reserved", c_int64),
                ("Time", c_int32),
                ("Symbol", c_char * 40),
                ("PreClosePrice", c_double),
                ("OpenPrice", c_double),
                ("HighPrice", c_double),
                ("LowPrice", c_double),
                ("LastPrice", c_double),
                ("ClosePrice", c_double),
                ("TradeStatus", c_char * 6),
                ("SecurityPhaseTag", c_char * 8),
                ("TotalNo", c_uint64),
                ("TotalVolume", c_uint64),
                ("TotalAmount", c_double),
                ("TotalBuyOrderVolume", c_uint64),
                ("WtAvgBuyPrice", c_double),
                ("BondWtAvgBuyPrice", c_double),
                ("TotalSellOrderVolume", c_uint64),
                ("WtAvgSellPrice", c_double),
                ("BondWtAvgSellPrice", c_double),
                ("IOPV", c_double),
                ("ETFBuyNo", c_int32),
                ("ETFBuyVolume", c_int64),
                ("ETFBuyAmount", c_double),
                ("ETFSellNo", c_int32),
                ("ETFSellVolume", c_int64),
                ("ETFSellAmount", c_double),
                ("YTM", c_double),
                ("TotalWarrantExecVol", c_int64),
                ("WarrantDownLimit", c_double),
                ("WarrantUpLimit", c_double),
                ("WithdrawBuyNo", c_int32),
                ("WithdrawBuyVolume", c_int64),
                ("WithdrawBuyAmount", c_double),
                ("WithdrawSellNo", c_int32),
                ("WithdrawSellVolume", c_int64),
                ("WithdrawSellAmount", c_double),
                ("TotalBuyNo", c_int32),
                ("TotalSellNo", c_int32),
                ("MaxBuyDuration", c_int32),
                ("MaxSellDuration", c_int32),
                ("BuyOrderNo", c_int32),
                ("SellOrderNo", c_int32),
                ("SellLevelNo", c_uint32),
                ("SellLevel", POINTER(BuySellLevelInfo3) * 10),
                ("SellLevelQueueNo01", c_uint32),
                ("SellLevelQueue", c_uint32 * 50),
                ("BuyLevelNo", c_uint32),
                ("BuyLevel", POINTER(BuySellLevelInfo3) * 10),
                ("BuyLevelQueueNo01", c_uint32),
                ("BuyLevelQueue", c_uint32 * 50)]


class SSEL2_Transaction(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Reserved", c_int64),
                ("TradeTime", c_int32),
                ("RecID", c_uint32),
                ("TradeChannel", c_int32),
                ("Symbol", c_char * 40),
                ("TradePrice", c_double),
                ("TradeVolume", c_uint32),
                ("TradeAmount", c_double),
                ("BuyRecID", c_int64),
                ("SellRecID", c_int64),
                ("BuySellFlag", c_char)]


class SSEL2_Index(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Reserved", c_int64),
                ("Time", c_int32),
                ("TradeTime", c_int32),
                ("Symbol", c_char * 40),
                ("PreClosePrice", c_double),
                ("OpenPrice", c_double),
                ("TotalAmount", c_double),
                ("HighPrice", c_double),
                ("LowPrice", c_double),
                ("LastPrice", c_double),
                ("TotalVolume", c_uint64),
                ("ClosePrice", c_double)]


class SSEL2_Auction(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Reserved", c_int64),
                ("Time", c_int32),
                ("Symbol", c_char * 40),
                ("OpenPrice", c_double),
                ("AuctionVolume", c_int64),
                ("LeaveVolume", c_int64),
                ("Side", c_char)]



class SSEL2_Overview(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Reserved", c_int64),
                ("Time", c_int32),
                ("Symbol", c_char * 40),
                ("MarketTime", c_int32),
                ("TradeDate", c_int32)]


class SZSEL2_Static(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Symbol", c_char * 40),
                ("SecurityName", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("SecurityEN", c_char * 40),
                ("ISINCode", c_char * 12),
                ("SymbolUnderlying", c_char * 20),
                ("UnderlyingSecurityIDSource", c_char * 4),
                ("SecurityType", c_int32),
                ("SecurityStatusTag", c_char * 20),
                ("PreClosePrice", c_double),
                ("ListingDate", c_int32),
                ("Currency", c_char * 5),
                ("ParValue", c_double),
                ("IssuedVolume", c_double),
                ("OutstandingShare", c_double),
                ("IndustryType", c_char * 5),
                ("PreYearEPS", c_double),
                ("YearEPS", c_double),
                ("OfferingFlag", c_char),
                ("NAV", c_double),
                ("CouponRate", c_double),
                ("IssuePrice", c_double),
                ("Interest", c_double),
                ("InterestAccrualDate", c_int32),
                ("MaturityDate", c_int32),
                ("ConversionPrice", c_double),
                ("ConversionPrice", c_double),
                ("ConversionBeginDate", c_int32),
                ("ConversionEndDate", c_int32),
                ("CallOrPut", c_char),
                ("WarrantClearingType", c_char),
                ("ClearingPrice", c_double),
                ("OptionType", c_char),
                ("EndDate", c_int32),
                ("ExpirationDays", c_int32),
                ("DayTrading", c_char),
                ("GageFlag", c_char),
                ("GageRate", c_double),
                ("CrdBuyUnderlying", c_char),
                ("CrdSellUnderlying", c_char),
                ("CrdPriceCheckType", c_char * 2),
                ("PledgeFlag", c_char),
                ("ContractMultiplier", c_double),
                ("RegularShare", c_char * 8),
                ("QualificationFlag", c_char),
                ("MarketMakerFlag", c_char),
                ("RoundLot", c_double),
                ("TickSize", c_double),
                ("BuyQtyUpperLimit", c_double),
                ("SellQtyUpperLimit", c_double),
                ("BuyVolumeUnit", c_double),
                ("SellVolumeUnit", c_double),
                ("OTC", POINTER(AuctionUpDown) * 3)]


class SZSEL2_Quotation(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Time", c_int64),
                ("Symbol", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("PreClosePrice", c_double),
                ("OpenPrice", c_double),
                ("LastPrice", c_double),
                ("HighPrice", c_double),
                ("LowPrice", c_double),
                ("PriceUpLimit", c_double),
                ("PriceDownLimit", c_double),
                ("PriceUpdown1", c_double),
                ("PriceUpdown2", c_double),
                ("TotalNo", c_uint64),
                ("TotalVolume", c_double),
                ("TotalAmount", c_double),
                ("ClosePrice", c_double),
                ("SecurityPhaseTag", c_char * 8),
                ("PERatio1", c_double),
                ("NAV", c_double),
                ("PERatio2", c_double),
                ("IOPV", c_double),
                ("PremiumRate", c_double),
                ("TotalSellOrderVolume", c_double),
                ("WtAvgSellPrice", c_double),
                ("SellLevelNo", c_uint32),
                ("SellLevel", POINTER(SZSE_BuySellLevelInfo3) * 10),
                ("SellLevelQueueNo01", c_uint32),
                ("SellLevelQueue", c_double * 50),
                ("TotalBuyOrderVolume", c_double),
                ("WtAvgBuyPrice", c_double),
                ("BuyLevelNo", c_uint32),
                ("BuyLevel", POINTER(SZSE_BuySellLevelInfo3) * 10),
                ("BuyLevelQueueNo01", c_uint32),
                ("BuyLevelQueue", c_double * 50)]


class SZSEL2_Transaction(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("SetID", c_uint32),
                ("RecID", c_uint64),
                ("BuyOrderID", c_uint64),
                ("SellOrderID", c_uint64),
                ("Symbol", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("TradeTime", c_int64),
                ("TradePrice", c_double),
                ("TradeVolume", c_double),
                ("TradeType", c_char)]


class SZSEL2_Index(Structure):
    _fields_ = [("QDSTime", c_uint64),
                ("Time", c_int64),
                ("Symbol", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("PreClosePrice", c_double),
                ("OpenPrice", c_double),
                ("HighPrice", c_double),
                ("LowPrice", c_double),
                ("LastPrice", c_double),
                ("TotalAmount", c_double),
                ("TotalNo", c_uint64),
                ("TotalVolume", c_double),
                ("SecurityPhaseTag", c_char * 8),
                ("SampleNo", c_uint32)]



class SZSEL2_Order(Structure):
    _fields_ = [("QDSTime", c_uint64), 
                ("SetID", c_uint32),
                ("RecID", c_uint64),
                ("Symbol", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("Time", c_int64),
                ("OrderPrice", c_double),
                ("OrderVolume", c_double),
                ("OrderCode", c_char),
                ("OrderType", c_char)]


class SZSEL2_Status(Structure):
    _fields_ = [("QDSTime", c_uint64), 
                ("Symbol", c_char * 40),
                ("SymbolSource", c_char * 5),
                ("Time", c_int64),
                ("FinancialStatus", c_char * 8),
                ("CrdBuyStatus", c_char),
                ("CrdSellStatus", c_char),
                ("SubscribeStatus", c_char),
                ("RedemptionStatus", c_char),
                ("PurchasingStatus", c_char),
                ("StockDiviStatus", c_char),
                ("PutableStatus", c_char),
                ("ExerciseStatus", c_char),
                ("GoldPurchase", c_char),
                ("GoldRedemption", c_char),
                ("AcceptedStatus", c_char),
                ("ReleaseStatus", c_char),
                ("CancStockDiviStatus", c_char),
                ("CancPutableStatus", c_char),
                ("PledgeStatus", c_char),
                ("RemovePledge", c_char),
                ("VoteStatus", c_char),
                ("StockPledgeRepo", c_char),
                ("DivideStatus", c_char),
                ("MergerStatus", c_char)]
